{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "triton-inference-server.fullname" . }}
  labels:
    {{- include "triton-inference-server.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "triton-inference-server.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{ toYaml .Values.autoscaling.metrics | indent 4 }}
{{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
