apiVersion: v1
kind: Service
metadata:
  name: {{ include "triton-inference-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "triton-inference-server.labels" . | nindent 4 }}
  {{- if or .Values.additionalAnnotations .Values.service.annotations }}
  annotations:
  {{- with .Values.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: triton-http
      port: {{ .Values.service.ports.http }}
      targetPort: http
    - name: triton-grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
    - name: triton-metrics
      port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
  selector:
    {{- include "triton-inference-server.selectorLabels" . | nindent 4 }}
