name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install helm-docs
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: norwoodj/helm-docs

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
